name: CI Rustdoc

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "Cargo.toml"
      - ".github/workflows/ci-rustdoc.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "Cargo.toml"
      - ".github/workflows/ci-rustdoc.yml"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: "-D warnings"

permissions:
  contents: read

jobs:
  rustdoc:
    name: cargo doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@7e38f4b43b4db5c8dd498af069a4f6196df1d067 # stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
      - name: Build docs
        run: cargo doc --features web --no-deps --document-private-items
        continue-on-error: true
      - name: Upload rustdoc
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: rustdoc
          path: target/doc
          if-no-files-found: ignore
